### ISSUE TITLE
Imena stolpcev in tidydata

### ISSUE THREAD

**Issue by timotejvesel** [zigagartner/APPR-2020-21#1]
Opazil sem, da v imenih stolpcev uporabljaš šumnike (npr. `Države`, `Domači`). Bolje bo, da se temu izogibaš in se omejiš na znake angleške abecede.
Poleg tega moraš tabele še pretvoriti v obliko `tida data` (v vsaki vrstici mora biti samo ena meritev).

**Comment by timotejvesel** [comment]
Rezultat tega, kar si naredil, je sicer pravilen, vendar obstaja precej lažja ter elegantnejša rešitev z uporabo funkcije `pivot_longer`, npr. nekaj takega
```r
kapacitete.vrste.obcin <- function(){
  uvoz <- read_csv2("podatki/kapacitete_vrste_obcin.csv", locale=locale(encoding="Windows-1250"),
                    col_names=c("Tip", letnice))[-c(1,2),]
  uvoz[, 1] <- tipi
  uvoz <- pivot_longer(uvoz, -Tip, names_to = "leto", values_to = "stevilo")

  return(uvoz)
}

kapacitete.vrste.obcin <- kapacitete.vrste.obcin()
```
Za ostale tabele podobno.

**Comment by zigagartner** [comment]
Hvala za nasvet, sem popravil.
