### ISSUE TITLE
Zaključek

### ISSUE THREAD

**Issue by zigagartner** [zigagartner/APPR-2020-21#3]
Pozdravljeni,
mislim, da je projekt zaključen. Pripombe in nasveti so dobrodošli.
Lep pozdrav,
Žiga

**Comment by timotejvesel** [comment]
Prvi in zadnji graf v poročilu sta brez podatkov. Sicer pa se mi zdi vredu.

**Comment by zigagartner** [comment]
Ali to pomeni, da grafa ne nariše?

**Comment by timotejvesel** [comment]
Ja, če ga odprem v binderju. V RStudiu pa dela vredu, tako, da bi moralo biti ok.

**Comment by jaanos** [comment]
Glede na to, da poročilo deluje, bom dodal povezavo do projekta na repozitorij za zagovore. Če se še nisi, se lahko z @alenFMF domeniš za termin zagovora. Če boš do takrat še kaj spreminjal, mi javi, da posodobim povezavo.

Svetujem, da sprejmeš pull request #4, da bo poročilo delovalo tudi v Binderju. Poleg tega predlagam, da na zadnji graf izrišeš tudi trendno črto.

**Comment by zigagartner** [comment]
Sprejel sem pull request in dodal trendno črto na zadnjem grafu.

**Comment by jaanos** [comment]
Bom posodobil povezavo - lahko pa vidiš, da nekaj ni v redu z zadnjim grafom, saj napovedne točke ne ležijo na trendni črti.

Najprej, opaziš lahko, da so tvoje napovedne točke skorajda na isti premici, kar nakazuje na to, da bo morda zadostoval linearen model. Če se vendarle odločiš za kubičen model, ustrezno napiši formulo: `Stevilo ~ Leto + I(Leto^2) + I(Leto^3)` pri `lm` in `formula=y ~ x + I(x^2) + I(x^3)` pri `geom_smooth`. Slednji funkciji dodaj še parameter `fullrange=TRUE`, da bo trendna črta zajela tudi napovedne točke.

Ena stvar, ki jo je treba paziti, je ta, da samih napovednih točk ne vključiš v podatke za izračun trendne črte - pri `ggplot` torej podaj `tabela_2` namesto `tabela_r`. Na ta način se napovedne točke ne bodo povezale s črto (to lahko sicer dosežeš tako, da k `geom_line` podaš parameter `data=tabela_r`), kar je načeloma čisto v redu (napovedne točke bodo na trendni črti, tako da črne črte med njimi tako ali tako ne bo videti).

Glavni razlog, da napovedne točke ne ležijo na trendni črti, pa je ta, da `geom_smooth` naredi trendno črto samo iz prikazanih podatkov (torej od leta 2000 naprej), medtem ko za `model` uporabiš podatke za vsa leta. Poskrbi torej, da se bodo uporabljeni podatki ujemali: bodisi na grafu prikaži vsa leta, ki jih imaš v podatkih, ali pa za gradnjo modela uporabi samo tiste podatke, ki jih prikazuješ.

**Comment by zigagartner** [comment]
Sem popravil.

**Comment by jaanos** [comment]
V redu, sem posodobil povezavo.

**Comment by zigagartner** [comment]
Hvala.
